apiVersion: v1
kind: Secret
metadata:
  name: master-secret-config
type: Opaque
data:
  postgres-password: yGGgdfafyUo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productShipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productShipping
  template:
    metadata:
      labels:
        app: productShipping
    spec:
      containers:
        - name: app
          image: nargeszirak/productShipping:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URL
              value: postgres.default:5432
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: master-secret-config
                  key: postgres-password
          imagePullPolicy: Always
      nodeSelector:
        role: master-node
---
# Expose Service
apiVersion: v1
kind: Service
metadata:
  name: productShipping
spec:
  selector:
    app: productShipping
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer