spring:
  datasource:
    url: jdbc:postgresql://postgres.default:8793/productShipping
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      autocommit: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect